/**
 * Backloggd filter vocabularies: slug → display name.
 *
 * These are the values the library/browse filter grammar expects, and they are NOT
 * guessable — `ps4--1` for PlayStation 4, `genesis-slash-megadrive` for Mega Drive. An
 * unrecognised slug makes Backloggd return HTTP 500 rather than an empty result, so
 * callers are validated against these tables before a request is made.
 *
 * Harvested from the `#plat-released-on` and `#genre` selects on a library page. Note
 * the option values there are unquoted HTML (`<option value=win>`), which a naive
 * `value="..."` regex silently misses.
 *
 * Regenerate with: npm run build:vocab
 */

export const PLATFORMS: Readonly<Record<string, string>> = Object.freeze({
  "win": "Windows PC",
  "mac": "Mac",
  "switch": "Nintendo Switch",
  "linux": "Linux",
  "ios": "iOS",
  "android": "Android",
  "ps4--1": "PlayStation 4",
  "xboxone": "Xbox One",
  "browser": "Web browser",
  "ps5": "PlayStation 5",
  "series-x-s": "Xbox Series X|S",
  "ps3": "PlayStation 3",
  "arcade": "Arcade",
  "ps2": "PlayStation 2",
  "dos": "DOS",
  "ps": "PlayStation",
  "xbox360": "Xbox 360",
  "nds": "Nintendo DS",
  "steam-vr": "SteamVR",
  "c64": "Commodore C64/128/MAX",
  "wii": "Wii",
  "psp": "PlayStation Portable",
  "amiga": "Amiga",
  "handheld": "Handheld Electronic LCD",
  "zxs": "ZX Spectrum",
  "psvita": "PlayStation Vita",
  "gba": "Game Boy Advance",
  "3ds": "Nintendo 3DS",
  "snes": "Super Nintendo Entertainment System",
  "acpc": "Amstrad CPC",
  "wiiu": "Wii U",
  "genesis-slash-megadrive": "Sega Mega Drive/Genesis",
  "nes": "NES",
  "mobile": "Legacy Mobile Device",
  "atari-st": "Atari ST/STE",
  "famicom": "Family Computer",
  "sfam": "Super Famicom",
  "gb": "Game Boy",
  "gbc": "Game Boy Color",
  "switch-2": "Nintendo Switch 2",
  "n64": "Nintendo 64",
  "meta-quest-2": "Meta Quest 2",
  "xbox": "Xbox",
  "appleii": "Apple II",
  "msx": "MSX",
  "e-reader-slash-card-e-reader": "e-Reader / Card-e Reader",
  "saturn": "Sega Saturn",
  "atari8bit": "Atari 8-bit",
  "ngc": "Nintendo GameCube",
  "pc-9800-series": "PC-9800 Series",
  "atari2600": "Atari 2600",
  "playdate": "Playdate",
  "plug-and-play": "Plug & Play",
  "dc": "Dreamcast",
  "nintendo-dsi": "Nintendo DSi",
  "psvr": "PlayStation VR",
  "winphone": "Windows Phone",
  "sms": "Sega Master System/Mark III",
  "psvr2": "PlayStation VR2",
  "pc-8800-series": "PC-8800 Series",
  "bbcmicro": "BBC Microcomputer System",
  "meta-quest-3": "Meta Quest 3",
  "satellaview": "Satellaview",
  "oculus-quest": "Oculus Quest",
  "stadia": "Google Stadia",
  "gamegear": "Sega Game Gear",
  "turbografx16--1": "TurboGrafx-16/PC Engine",
  "oculus-rift": "Oculus Rift",
  "sharp-x68000": "Sharp X68000",
  "oculus-vr": "Oculus VR",
  "3do": "3DO Interactive Multiplayer",
  "turbografx-16-slash-pc-engine-cd": "Turbografx-16/PC Engine CD",
  "fm-towns": "FM Towns",
  "sega-cd": "Sega CD",
  "fm-7": "FM-7",
  "fds": "Family Computer Disk System",
  "msx2": "MSX2",
  "vic-20": "Commodore VIC-20",
  "x1": "Sharp X1",
  "trs-80": "TRS-80",
  "colecovision": "ColecoVision",
  "c16": "Commodore 16",
  "intellivision": "Intellivision",
  "amiga-cd32": "Amiga CD32",
  "ouya": "Ouya",
  "neogeoaes": "Neo Geo AES",
  "acorn-electron": "Acorn Electron",
  "philips-cdi": "Philips CD-i",
  "windows-mixed-reality": "Windows Mixed Reality",
  "dvd-player": "DVD Player",
  "apple-iigs": "Apple IIGS",
  "sinclair-zx81": "Sinclair ZX81",
  "hyperscan": "HyperScan",
  "ti-99": "Texas Instruments TI-99",
  "trs-80-color-computer": "TRS-80 Color Computer",
  "atari5200": "Atari 5200",
  "neogeomvs": "Neo Geo MVS",
  "sg1000": "SG-1000",
  "wonderswan": "WonderSwan",
  "neo-geo-cd": "Neo Geo CD",
  "lynx": "Atari Lynx",
  "blackberry": "BlackBerry OS",
  "arduboy": "Arduboy",
  "odyssey-2-slash-videopac-g7000": "Odyssey 2 / Videopac G7000",
  "neo-geo-pocket-color": "Neo Geo Pocket Color",
  "c-plus-4": "Commodore Plus/4",
  "wonderswan-color": "WonderSwan Color",
  "firetv": "Amazon Fire TV",
  "evercade": "Evercade",
  "jaguar": "Atari Jaguar",
  "dragon-32-slash-64": "Dragon 32/64",
  "atari7800": "Atari 7800",
  "new-3ds": "New Nintendo 3DS",
  "vectrex": "Vectrex",
  "nec-pc-6000-series": "NEC PC-6000 Series",
  "windows-mobile": "Windows Mobile",
  "leapster": "Leapster",
  "acorn-archimedes": "Acorn Archimedes",
  "uzebox": "Uzebox",
  "watara-slash-quickshot-supervision": "Watara/QuickShot Supervision",
  "leapster-explorer-slash-leadpad-explorer": "Leapster Explorer/LeadPad Explorer",
  "ngage": "N-Gage",
  "virtualboy": "Virtual Boy",
  "pc-fx": "PC-FX",
  "g-and-w": "Game & Watch",
  "visionos": "visionOS",
  "advanced-pico-beena": "Advanced Pico Beena",
  "sega-pico": "Sega Pico",
  "apple-pippin": "Apple Pippin",
  "sega32": "Sega 32X",
  "64dd": "64DD",
  "cpet": "Commodore PET",
  "arcadia-2001": "Arcadia 2001",
  "apcw": "Amstrad PCW",
  "legacy-computer": "Legacy Computer",
  "sharp-mz-2200": "Sharp MZ-2200",
  "zeebo": "Zeebo",
  "vc-4000": "VC 4000",
  "fairchild-channel-f": "Fairchild Channel F",
  "gear-vr": "Gear VR",
  "vsmile": "V.Smile",
  "mega-duck-slash-cougar-boy": "Mega Duck/Cougar Boy",
  "astrocade": "Bally Astrocade",
  "gamate": "Gamate",
  "pokemon-mini": "Pok\u00e9mon mini",
  "odyssey--1": "Odyssey",
  "atari-jaguar-cd": "Atari Jaguar CD",
  "elektor-tv-games-computer": "Elektor TV Games Computer",
  "playdia": "Playdia",
  "laseractive": "LaserActive",
  "epoch-super-cassette-vision": "Epoch Super Cassette Vision",
  "palm-os": "Palm OS",
  "tomy-tutor-slash-pyuta-slash-grandstand-tutor": "Tomy Tutor / Pyuta / Grandstand Tutor",
  "game-dot-com": "Game.com",
  "terebikko-slash-see-n-say-video-phone": "Terebikko / See 'n Say Video Phone",
  "r-zone": "R-Zone",
  "ooparts": "OOParts",
  "gizmondo": "Gizmondo",
  "visual-memory-unit-slash-visual-memory-system": "Visual Memory Unit / Visual Memory System",
  "intellivision-amico": "Intellivision Amico",
  "digiblast": "Digiblast",
  "daydream": "Daydream",
  "oculus-go": "Oculus Go",
  "super-acan": "Super A'Can",
  "1292-advanced-programmable-video-system": "1292 Advanced Programmable Video System",
  "neo-geo-pocket": "Neo Geo Pocket",
  "commodore-cdtv": "Commodore CDTV",
  "thomson-mo5": "Thomson MO5",
  "pocketstation": "PocketStation",
  "blu-ray-player": "Blu-ray Player",
  "polymega": "Polymega",
  "zod": "Tapwave Zodiac",
  "onlive": "OnLive Game System",
  "tatung-einstein": "Tatung Einstein",
  "leaptv": "LeapTV",
  "pdp10": "PDP-10",
  "duplicate-stadia": "DUPLICATE Stadia",
  "plato--1": "PLATO",
  "epoch-cassette-vision": "Epoch Cassette Vision",
  "microvision--1": "Microvision",
  "pc-50x-family": "PC-50X Family",
  "casio-loopy": "Casio Loopy",
  "supergrafx": "PC Engine SuperGrafx",
  "pdp11": "PDP-11",
  "panasonic-m2": "Panasonic M2",
  "sega-cd-32x": "Sega CD 32X",
  "call-a-computer": "Call-A-Computer time-shared mainframe computer system",
  "nuon": "Nuon",
  "airconsole": "AirConsole",
  "super-nes-cd-rom-system": "Super NES CD-ROM System",
  "sinclair-ql": "Sinclair QL",
  "hyper-neo-geo-64": "Hyper Neo Geo 64",
  "hp2100": "HP 2100",
  "ay-3-8500": "AY-3-8500",
  "ay-3-8610": "AY-3-8610",
  "psn": "PlayStation Network",
  "microcomputer--1": "Microcomputer",
  "vc": "Virtual Console",
  "gx4000": "Amstrad GX4000",
  "exidy-sorcerer": "Exidy Sorcerer",
  "ay-3-8760": "AY-3-8760",
  "panasonic-jungle": "Panasonic Jungle",
  "sol-20": "Sol-20",
  "pdp-8--1": "PDP-8",
  "edsac--1": "EDSAC",
  "imlac-pds1": "Imlac PDS-1",
  "cdccyber70": "CDC Cyber 70",
  "pdp-7--1": "PDP-7",
  "analogueelectronics": "Analogue electronics",
  "ay-3-8606": "AY-3-8606",
  "nimrod": "Ferranti Nimrod Computer",
  "ay-3-8605": "AY-3-8605",
  "steam-deck": "Steam Deck",
  "ay-3-8607": "AY-3-8607",
  "ay-3-8603": "AY-3-8603",
  "xla": "Xbox Live Arcade",
  "gt40": "DEC GT40",
  "donner30": "Donner Model 30",
  "pdp1": "PDP-1",
  "nintendo-eshop": "Nintendo eShop",
  "sdssigma7": "SDS Sigma 7",
  "wiiware": "WiiWare",
  "handheld-console": "Handheld Console",
  "steam--1": "SteamOS",
  "hp3000": "HP 3000",
  "ay-3-8710": "AY-3-8710",
});

export const GENRES: Readonly<Record<string, string>> = Object.freeze({
  "adventure": "Adventure",
  "arcade": "Arcade",
  "hack-and-slash-beat-em-up": "Brawler",
  "card-and-board-game": "Card & Board Game",
  "fighting": "Fighting",
  "indie": "Indie",
  "moba": "MOBA",
  "music": "Music",
  "pinball": "Pinball",
  "platform": "Platform",
  "point-and-click": "Point-and-Click",
  "puzzle": "Puzzle",
  "quiz-trivia": "Quiz/Trivia",
  "racing": "Racing",
  "real-time-strategy-rts": "Real Time Strategy",
  "role-playing-rpg": "RPG",
  "shooter": "Shooter",
  "simulator": "Simulator",
  "sport": "Sport",
  "strategy": "Strategy",
  "tactical": "Tactical",
  "turn-based-strategy-tbs": "Turn Based Strategy",
  "visual-novel": "Visual Novel",
});

/** Game categories accepted by the `category:` filter. */
export const CATEGORIES = [
  "main_game", "dlc", "expansion", "standalone_expansion", "expanded_game",
  "remake", "remaster", "port", "fork", "mod", "episode", "season", "bundle", "update",
] as const;

export type Category = (typeof CATEGORIES)[number];
